apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-bw
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: $EMAIL_ADDRESS
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-bw
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bw-pv-claim
  namespace: bitwardenrs
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $VOLUME_SIZE
---
apiVersion: v1
kind: Service
metadata:
  name: bw-service
  namespace: bitwardenrs
spec:
  selector:
    app: bw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: bitwardenrs-database-url
  namespace: bitwardenrs
data:
  DATABASE_URL: dXBkYXRlLXRoaXMtYWZ0ZXItaW5zdGFsbGF0aW9uCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw
  namespace: bitwardenrs
  labels:
    app: bw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bw
  template:
    metadata:
      labels:
        app: bw
    spec:
      containers:
        - name: bw
          image: bitwardenrs/server-mysql:1.19.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bitwardenrs-database-url
                  key: DATABASE_URL
          volumeMounts:
            - name: bw-persistent-storage
              mountPath: /data

      volumes:
        - name: bw-persistent-storage
          persistentVolumeClaim:
            claimName: bw-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-bw
    ingress.kubernetes.io/ssl-redirect: "true"
  name: bw
  namespace: bitwardenrs
spec:
  tls:
    - hosts:
        - bw.$DOMAIN_NAME
      secretName: letsencrypt-prod-bw
  rules:
    - host: bw.$DOMAIN_NAME
      http:
        paths:
          - backend:
              serviceName: bw-service
              servicePort: 80
