apiVersion: v1
kind: Namespace
metadata:
  name: z-app-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: z-app-1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
