# ********
# README
# ********
# When you are updating Jenkins image e.g. from 2.190.1 to 2.263.3,
# please also update the version in the init container. There are
# two (2) occurrence of version number in this file. Update them all.
# Tip: use `Ctrl/Cmd + F` to search them.

apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
  labels:
    type: longhorn
    app: jenkins
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $VOLUME_SIZE
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-frontend
  namespace: jenkins
spec:
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
    - name: jenkins-agent
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: jenkins
    spec:
      initContainers:
        - name: update-jenkins
          image: alpine:latest
          command: ["sh", "-c"]
          args:
            - if [ -d "/bitnami/jenkins" ]; then
              apk add --update curl && rm -rf /var/cache/apk/*;
              cd /bitnami/jenkins;
              curl -L https://get.jenkins.io/war-stable/2.263.4/jenkins.war -o jenkins.war;
              chown -R 1001:1001 .;
              fi;
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /bitnami
      containers:
        - image: bitnami/jenkins:2.190.1-debian-9-r14
          name: jenkins
          env:
            - name: JENKINS_USERNAME
              value: $JENKINS_USERNAME
            - name: JENKINS_PASSWORD
              value: $JENKINS_PASSWORD
          ports:
            - containerPort: 8080
              name: jenkins
            - containerPort: 50000
              name: jenkins-agent
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /bitnami
      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
