apiVersion: v1
kind: Namespace
metadata:
  name: z-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: z-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: RANDOM_WORDS
              value: $RANDOM_WORDS
            - name: VERSION
              value: 0.0.16
